name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          yarn
          yarn build

      - name: Deploy Mushus.github.io
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "Get the repository logs"
          COMMIT_SUMMARY=$(git log -1 --pretty='%s')
          COMMIT_ID=$(git rev-parse HEAD)

          echo "Put the deploy key"
          mkdir -p /home/runner/.ssh/
          echo -e "$DEPLOY_KEY" > /home/runner/.ssh/deploykey
          chmod 600 /home/runner/.ssh/deploykey

          echo "Commit changes"
          cd src/.vuepress/dist/
          git init
          git config --local user.name "Github Actions"
          git config --local user.email "noreply@github.com"
          git config --local core.sshCommand "ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/deploykey -F /dev/null"
          git remote add origin git@github.com:Mushus/Mushus.github.io.git
          git fetch
          git reset --soft refs/remote/origin/master || :
          ret=$?
          if [ "$ret" -eq "0" ]; then
            git diff --quiet || :
            ret=$?
            if [ "$ret" -eq "0" ]; then
              echo "not updated" && exit 1
            fi
          fi
          git add .
          git commit -m $COMMIT_SUMMARY -m "See Detail: https://github.com/Mushus/ghp/commit/${COMMIT_ID}"
          git push orign master
